name: project
on:
  push:
   branches:
   - main
jobs:
   action-for-demo:
     runs-on: ubuntu-latest
     
     steps:
     - name: checkout code
       uses: actions/checkout@v4
       
     - name: print index.html file
       run: echo " hello jay mahakal" 
