name: inputs demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy
        required: true
        default: dev
        type: choice
        options:
          - main
          - developer
          - prod

      artifact_tag:
        description: Choose the git tag to deploy
        required: true

jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: |
          echo "Deploying the ${{ inputs.artifact_tag }} app application to ${{ inputs.environment }}"
